- name: Docker Login to Docker Hub
  docker_login:
    registry_url: "{{ docker_registry }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: Copy Docker Compose file to EC2 instance
  copy:
    src: "docker-compose.yaml"
    dest: "/home/ec2-user/docker-compose.yml"
    owner: bilal
    group: bilal
    mode: '0644'

- name: Start container using Docker Compose v2
  community.docker.docker_compose_v2:
    project_src: /home/bilal
    state: present