---
- name: Wait For SSH To Open
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for ssh to open
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
        timeout: 300
      vars:
        ansible_connection: local


- name: Install Docker and Docker Compose v2
  hosts: all
  become: yes
  vars:
    compose_plugin_path: /usr/libexec/docker/cli-plugins/docker-compose
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present
        update_cache: yes

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Create Docker CLI plugins directory
      file:
        path: /usr/libexec/docker/cli-plugins
        state: directory
        mode: '0755'

    - name: Download Docker Compose v2 plugin
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.37.0/docker-compose-linux-x86_64
        dest: "{{ compose_plugin_path }}"
        mode: '0755'

- name: Create new linux user
  hosts: all
  become: yes
  roles:
    - create_user

- name: Start Docker Containers
  hosts: all
  vars_files:
    - project-vars
  roles:
    - start_container