name: Destroy Terraform Infrastructure

on:
  workflow_dispatch: 
    # branches: [ "main" ]

permissions:
  contents: read

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      # - name: Fail if not on main branch
      #   run: |
      #     echo "Branch: ${GITHUB_REF##*/}"
      #     if [ "${GITHUB_REF##*/}" != "main" ]; then
      #       echo "⛔ This workflow can only be run on the main branch."
      #       exit 1
      #     fi

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_NAME }}
          aws-region: ap-south-1

      - name: Terraform Init (reads remote state)
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform
