name: Test Deploy AWS Infrastructure via OIDC

on:
  workflow_dispatch:
  push:
    branches: [ "aws_oidc_configration" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Development Infrastruce Provisioning Using Terraform'
    runs-on: ubuntu-latest
    environment: development

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Fail if not on AWS_OIDC branch
      run: |
        echo "Branch: ${GITHUB_REF##*/}"
        if [ "${GITHUB_REF##*/}" != "aws_oidc_configration" ]; then
          echo "⛔ This workflow can only be run on the aws_oidc_configration branch."
          exit 1
        fi
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
        
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_NAME }}
        aws-region: ap-south-1

    - name: Writing tfvars
      working-directory: ./terraform
      run: |
          cat <<EOF > terraform.tfvars
          vpc_cidr_block = "10.0.0.0/16"
          subnet_cidr_block = "10.0.10.0/24"
          availability_zone = "ap-south-1a"
          env_prefix = "github-actions-dev"
          instance_type = "t2.micro"

    - name: Get SSH KEY AND SET PERMISSION
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Format
      run: terraform fmt -recursive
      working-directory: ./terraform

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform

    - name: Writing vars file for ansible start container role
      working-directory: ./ansible/roles/start_container
      run: |
          mkdir vars
          cd vars
          cat <<EOF > main.yaml
          docker_registry: "${{ secrets.DOCKER_REGISTRY }}"
          docker_username: "${{ secrets.DOCKER_USERNAME }}"
          docker_password: "${{ secrets.DOCKER_PASSWORD }}"
          EOF

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
